#!/bin/bash

# Copyright 2020 University of California, Riverside
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
LOG4J=$(find $DIR -depth -maxdepth 3 -iname 'log4j-*.xml' -print -quit)
if [ -z "$1" ]; then
  CMD=server
else
  CMD=$@
fi
STARJAR=$(find $DIR -depth -maxdepth 2 -iname 'ucrstar-*.jar' -print -quit)
cmd="beast --conf spark.driver.extraJavaOptions=-Dlog4j.configuration=file://$LOG4J \
    --packages org.mongodb:mongodb-driver-sync:3.12.0,org.mongodb:mongo-java-driver:3.12.0 \
    com.googlecode.json-simple:json-simple:1.1.1,javax:javaee-api:7.0 \
    --jars $STARJAR $CMD"

# Run the command
$cmd